version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: lastmetro-db
    environment:
      POSTGRES_DB: dernier_metro
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    ports:
      - "5432:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d dernier_metro"]
      interval: 5s
      timeout: 3s
      retries: 5

  api:
    build: .
    container_name: lastmetro-api
    environment:
      PORT: 3000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: dernier_metro
      DB_USER: app
      DB_PASSWORD: app
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pgdata:
